version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: gitfix-redis
    ports:
      - '6380:6379'
    volumes:
      - redis_data:/data
    networks:
      - gitfix-net

  daemon:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: gitfix-daemon
    command: npm run daemon
    volumes:
      - .:/usr/src/app
      - /tmp/git-processor:/tmp/git-processor
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - gitfix-net

  worker:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: gitfix-worker
    command: npm run worker
    volumes:
      - .:/usr/src/app
      - /tmp/git-processor:/tmp/git-processor
      - ~/.claude:/root/.claude
      - /var/run/docker.sock:/var/run/docker.sock
      - claude_logs:/tmp/claude-logs
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - gitfix-net

  web-ui:
    build:
      context: ./gitfix-ui
      dockerfile: Dockerfile
    container_name: gitfix-web-ui
    ports:
      - '5173:5173'
    environment:
      - VITE_API_URL=http://dashboard-api:4000
    networks:
      - gitfix-net

  dashboard-api:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: gitfix-dashboard-api
    command: sh -c "cd /usr/src/app/packages/dashboard && node server.js"
    ports:
      - '4000:4000'
    volumes:
      - .:/usr/src/app
      - ~/.claude:/root/.claude:ro
      - claude_logs:/tmp/claude-logs:ro
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - gitfix-net

  dashboard-client:
    build:
      context: ./packages/dashboard/client
      dockerfile: Dockerfile
    container_name: gitfix-dashboard-client
    ports:
      - '5174:5173'
    environment:
      - VITE_API_URL=http://dashboard-api:4000
    depends_on:
      - dashboard-api
    networks:
      - gitfix-net

networks:
  gitfix-net:
    driver: bridge

volumes:
  redis_data:
  claude_logs: