version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: gitfix-redis
    ports:
      - '6379:6379'
    networks:
      - gitfix-net

  watcher:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gitfix-watcher
    command: npm run daemon
    volumes:
      - .:/usr/src/app
      - /tmp/git-processor:/tmp/git-processor
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - gitfix-net

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gitfix-worker
    command: npm run worker
    volumes:
      - .:/usr/src/app
      - /tmp/git-processor:/tmp/git-processor
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - gitfix-net

  web-ui:
    build:
      context: ./gitfix-ui
      dockerfile: Dockerfile
    container_name: gitfix-web-ui
    ports:
      - '5173:5173'
    networks:
      - gitfix-net

networks:
  gitfix-net:
    driver: bridge