version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: gitfix-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - gitfix-net

  daemon:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: gitfix-daemon
    command: npm run daemon
    volumes:
      - .:/usr/src/app
      - /tmp/git-processor:/tmp/git-processor
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - gitfix-net

  worker:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: gitfix-worker
    command: npm run worker
    volumes:
      - .:/usr/src/app
      - /tmp/git-processor:/tmp/git-processor
      - ~/.claude:/root/.claude
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - gitfix-net

  web-ui:
    build:
      context: ./gitfix-ui
      dockerfile: Dockerfile
    container_name: gitfix-web-ui
    ports:
      - '5173:5173'
    networks:
      - gitfix-net

  dashboard-api:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: gitfix-dashboard-api
    command: node packages/dashboard/server.js
    ports:
      - '4000:4000'
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - gitfix-net

networks:
  gitfix-net:
    driver: bridge

volumes:
  redis_data: